CREATE DATABASE QuanLiThuvien
GO
USE QuanLiThuvien
GO
CREATE TABLE SACH
(
MASACH CHAR(10) NOT NULL,
TENSACH NVARCHAR(30),
TENTG NVARCHAR(30),
NAMXB DATE,
SOTRANG INT,
THELOAI NVARCHAR(30),
PRIMARY KEY(MASACH)
)
GO
CREATE TABLE DOCGIA
(
MADG CHAR(10) NOT NULL,
TENDG NVARCHAR(30),
NGAYSINH DATE,
DIACHI NVARCHAR(30),
CHUYENNGANH NVARCHAR(30),
PRIMARY KEY(MADG)
)
GO
CREATE TABLE CUNGCAP
(
MANHACC CHAR(10) NOT NULL,
TENNHACUNGCAP NVARCHAR(30),
SOBAN INT,
PRIMARY KEY(MANHACC)
)
GO
 CREATE TABLE MUONTRA
 (
 MASACH CHAR(10) FOREIGN KEY(MASACH) REFERENCES dbo.SACH(MASACH),
 MADG CHAR(10) FOREIGN KEY(MADG) REFERENCES dbo.DOCGIA(MADG),
 NGAYMUON DATE,
 HENTRA DATE,
 NGAYTRA DATE,
 PRIMARY KEY(MASACH,MADG,NGAYMUON)
 )
 GO
 CREATE TABLE CHITIETGIAODICH
 (
 MASACH CHAR(10) FOREIGN KEY(MASACH) REFERENCES dbo.SACH(MASACH),
 MANHACC CHAR(10) FOREIGN KEY(MANHACC) REFERENCES dbo.CUNGCAP(MANHACC),
 NGAYGIAODICH DATE,
 
 
 )
 GO
 